- README.md
> Signin myprofile capuras

- README.md
> UPDATED KYLA

- README.md
> Login myprofile chavez

- package-lock.json
- package.json
- src/App.jsx
- src/backendApi/AuthContext.jsx
- src/backendApi/AuthService.js
- src/backendApi/AxiosConfig.js
- src/backendApi/NotificationContext.jsx
- src/components/HomePage.jsx
- src/components/Notification.jsx
- src/components/ProtectedRoute.jsx
- src/components/SplashScreen/AuthModal.jsx
- src/components/SplashScreen/FormInput.jsx
- src/components/SplashScreen/LoadingSreen.jsx
- src/components/SplashScreen/SignIn.jsx
- src/components/SplashScreen/VerifyEmail.jsx
> did many things

- .env
- index.html
- src/App.jsx
- src/auth/OAuth2RedirectHandler.jsx
- src/backendApi/AuthContext.jsx
- src/components/AboutUs.jsx
- src/components/ProtectedRoute.jsx
- src/components/SplashScreen/AuthModal.jsx
- src/components/SplashScreen/Footer.jsx
- src/components/SplashScreen/ScrollToTop.jsx
Done Social Logins maybe fix the Microsoft
> Done Social Logins

- frontend/src/App.jsx
- frontend/src/backendApi/AuthContext.jsx
- frontend/src/components/HomePage.jsx
- frontend/src/components/ProtectedRoute.jsx
- frontend/src/components/SplashScreen/ClassDetails.jsx
- frontend/src/components/SplashScreen/CreateClass.jsx
- frontend/src/components/SplashScreen/PublicSearch.jsx
- frontend/src/components/SplashScreen/SignIn.jsx
- frontend/src/components/SplashScreen/YourClasses.jsx
> creating classes

- frontend/src/components/SplashScreen/CategorySection.jsx
> Added gitignore for all

- README.md
> README.md description

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/SplashScreen/YourClasses.jsx
- frontend/src/styles/YourClasses.css
- frontend/tailwind.config.js
> Making Cooler the Classes

- frontend/src/components/HomePage.jsx
- frontend/src/components/Profile.jsx
- frontend/src/components/SplashScreen/YourClasses.jsx
Design the notification and Homepage
> Design the notification and Homepage

- frontend/src/components/HomePage.jsx
- frontend/src/components/Profile.jsx
- frontend/src/components/SplashScreen/ClassDetails.jsx
- frontend/src/components/SplashScreen/CreateClass.jsx
- frontend/src/components/SplashScreen/Footer.jsx
- frontend/src/components/SplashScreen/LessonView.jsx
- frontend/src/components/SplashScreen/YourClasses.jsx
> Frontend Design

- frontend_mobile/frontend_mobile/.idea/.gitignore
- frontend_mobile/frontend_mobile/.idea/deploymentTargetSelector.xml
- frontend_mobile/frontend_mobile/.idea/gradle.xml
- frontend_mobile/frontend_mobile/.idea/kotlinc.xml
- frontend_mobile/frontend_mobile/.idea/migrations.xml
- frontend_mobile/frontend_mobile/.idea/runConfigurations.xml
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/HomePage.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/MainActivity.kt
- frontend_mobile/frontend_mobile/app/src/main/res/drawable/ic_arrow_forward.xml
- frontend_mobile/frontend_mobile/app/src/main/res/drawable/ic_category.xml
> updated mobile

- frontend/src/App.jsx
- frontend/src/components/EditProfile.jsx
- frontend/src/components/HomePage.jsx
- frontend/src/components/Profile.jsx
> Editprofile and minor changes

- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/MainActivity.kt
> Fix mobile

- backend/src/main/java/com/example/neighbornetbackend/config/SecurityConfig.java
- backend/src/main/java/com/example/neighbornetbackend/controller/ClassController.java
- backend/src/main/java/com/example/neighbornetbackend/controller/LessonController.java
- backend/src/main/java/com/example/neighbornetbackend/dto/ClassResponse.java
- backend/src/main/java/com/example/neighbornetbackend/dto/LessonResponse.java
- backend/src/main/java/com/example/neighbornetbackend/dto/RatingRequest.java
- backend/src/main/java/com/example/neighbornetbackend/dto/RatingResponse.java
- backend/src/main/java/com/example/neighbornetbackend/model/ClassEnrollment.java
- backend/src/main/java/com/example/neighbornetbackend/model/ClassRating.java
- backend/src/main/java/com/example/neighbornetbackend/model/CourseClass.java
- backend/src/main/java/com/example/neighbornetbackend/model/Lesson.java
- backend/src/main/java/com/example/neighbornetbackend/model/LessonRating.java
- backend/src/main/java/com/example/neighbornetbackend/repository/ClassEnrollmentRepository.java
- backend/src/main/java/com/example/neighbornetbackend/repository/LessonRatingRepository.java
- backend/src/main/java/com/example/neighbornetbackend/repository/RatingRepository.java
- backend/src/main/java/com/example/neighbornetbackend/service/ClassService.java
- backend/src/main/java/com/example/neighbornetbackend/service/LessonService.java
- backend/src/main/java/com/example/neighbornetbackend/service/RatingService.java
- frontend/src/components/SplashScreen/ClassDetails.jsx
- frontend/src/components/SplashScreen/LessonView.jsx
- frontend/src/components/SplashScreen/StarRating.jsx
> Rating And Fix ClassDetails

- frontend/src/App.jsx
- frontend/src/components/AddBorrowingItem.jsx
- frontend/src/components/Borrowing.jsx
> Added heads up Borriwng

- frontend/src/components/Borrowing.jsx
- frontend/src/components/SplashScreen/ExpertsSection.jsx
- frontend/src/components/SplashScreen/ExploreOnlineSection.jsx
> Landing page and minor changes

- frontend/src/components/HomePage.jsx
> Added Search query

- backend/src/main/java/com/example/neighbornetbackend/controller/ItemController.java
- backend/src/main/java/com/example/neighbornetbackend/dto/BorrowRequestDTO.java
- backend/src/main/java/com/example/neighbornetbackend/service/ItemService.java
- frontend/src/App.jsx
- frontend/src/components/Borrowing.jsx
- frontend/src/components/ItemDetail.jsx
> Notification myprofile capuras

- frontend/src/components/Borrowing.jsx
> Messaging myprofile capuras

- frontend/src/components/BorrowedItems.jsx
- frontend/src/components/Dashboard.jsx
- frontend/src/components/YourItems.jsx
> Dashboard, BorrowingItems, YourItems

- backend/.env.example
- backend/.gitignore
- backend/pom.xml
- backend/src/main/resources/application.properties
> Added Secure

- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/HomePage.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/api/ChatApiService.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/auth/ChatViewModel.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/repository/ChatRepository.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/utils/MessageComponents.kt
Done Messaging both mobile and Web real-time
> Done Messaging both mobile and Web real-time

- backend/src/main/java/com/example/neighbornetbackend/config/SecurityConfig.java
- backend/src/main/java/com/example/neighbornetbackend/controller/AdminController.java
- backend/src/main/java/com/example/neighbornetbackend/controller/ClassController.java
- backend/src/main/java/com/example/neighbornetbackend/model/UserRole.java
- backend/src/main/java/com/example/neighbornetbackend/repository/ClassRepository.java
- backend/src/main/java/com/example/neighbornetbackend/security/JwtTokenProvider.java
- frontend/src/App.jsx
- frontend/src/backendApi/AuthContext.jsx
- frontend/src/components/AdminDashboard.jsx
- frontend/src/components/AdminLogin.jsx
- frontend/src/components/AdminRoute.jsx
- frontend/src/components/SplashScreen/AuthModal.jsx
- frontend/src/components/SplashScreen/SignIn.jsx
> Tommorow for admin work

- backend/src/main/java/com/example/neighbornetbackend/controller/AuthController.java
- backend/src/main/java/com/example/neighbornetbackend/controller/UserManagementController.java
- backend/src/main/java/com/example/neighbornetbackend/controller/UserProfileController.java
- backend/src/main/java/com/example/neighbornetbackend/dto/UserResponse.java
- backend/src/main/java/com/example/neighbornetbackend/model/User.java
- backend/src/main/java/com/example/neighbornetbackend/repository/UserRepository.java
- backend/src/main/java/com/example/neighbornetbackend/security/JwtAuthenticationFilter.java
- backend/src/main/java/com/example/neighbornetbackend/service/UserDeletionService.java
- frontend/src/backendApi/AuthService.js
- frontend/src/components/AdminLogin.jsx
- frontend/src/components/Dashboard.jsx
- frontend/src/components/EditProfile.jsx
- frontend/src/components/HomePage.jsx
- frontend/src/components/SettingsView.jsx
- frontend/src/components/SplashScreen/AuthModal.jsx
- frontend/src/components/UsersView.jsx
> Done Admin

- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/HomePage.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/api/ProfileApiService.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/auth/ProfileViewModel.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/di/AppModule.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/di/NetworkModule.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/network/Models.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/utils/MessageComponents.kt
Polishing mobile and added Profile Content
> Polishing mobile and added Profile Content

- frontend/src/components/Toast.jsx
> Testing if it's stop

- backend/src/main/java/com/example/neighbornetbackend/config/FirebaseMessagingConfig.java
- backend/src/main/java/com/example/neighbornetbackend/controller/FCMController.java
- backend/src/main/java/com/example/neighbornetbackend/dto/FCMTokenRequest.java
- backend/src/main/java/com/example/neighbornetbackend/model/User.java
- backend/src/main/java/com/example/neighbornetbackend/service/ChatServiceImpl.java
- backend/src/main/java/com/example/neighbornetbackend/service/FCMService.java
- backend/src/main/java/com/example/neighbornetbackend/service/NotificationService.java
- frontend_mobile/frontend_mobile/app/build.gradle.kts
- frontend_mobile/frontend_mobile/app/src/main/AndroidManifest.xml
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/MyApplication.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/api/FCMApi.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/di/NetworkModule.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/network/FCMService.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/network/Models.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/utils/NotificationChannels.kt
- frontend_mobile/frontend_mobile/app/src/main/res/drawable/ic_notification.xml
- frontend_mobile/frontend_mobile/app/src/main/res/drawable/ic_notification_status.xml
- frontend_mobile/frontend_mobile/app/src/main/res/values/strings.xml
> Done push notification

- frontend/src/backendApi/NotificationContext.jsx
- frontend/src/backendApi/NotificationService.js
Im trying to fix the notif pero okay nato
> Im trying to fix the notif pero okay nato

- backend/pom.xml
- backend/src/main/java/com/example/neighbornetbackend/config/HmsConfig.java
- backend/src/main/java/com/example/neighbornetbackend/controller/RoomController.java
- backend/src/main/java/com/example/neighbornetbackend/dto/CreateRoomRequest.java
- backend/src/main/java/com/example/neighbornetbackend/dto/RoomCodeDTO.java
- backend/src/main/java/com/example/neighbornetbackend/dto/RoomResponse.java
- backend/src/main/java/com/example/neighbornetbackend/model/Room.java
- backend/src/main/java/com/example/neighbornetbackend/model/RoomCodes.java
- backend/src/main/java/com/example/neighbornetbackend/repository/RoomCodesRepository.java
- backend/src/main/java/com/example/neighbornetbackend/repository/RoomRepository.java
- backend/src/main/java/com/example/neighbornetbackend/service/HmsWebClientService.java
- backend/src/main/java/com/example/neighbornetbackend/service/RoomService.java
- backend/src/main/resources/application.properties
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.jsx
- frontend/src/components/HomePage.jsx
- frontend/src/components/StudyRooms.jsx
> Done study room

- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/LoginScreen.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/MainActivity.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/api/ForgotPasswordApi.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/auth/ForgotPasswordViewModel.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/di/NetworkModule.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/network/Models.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/network/Resource.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/repository/AuthRepository.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/utils/ForgotPasswordScreen.kt
> Forgot Password mobile 90

- backend/pom.xml
- backend/src/main/java/com/example/neighbornetbackend/controller/FileUploadController.java
- backend/src/main/java/com/example/neighbornetbackend/controller/QuizGenerationController.java
- backend/src/main/java/com/example/neighbornetbackend/dto/ContentImportRequest.java
- backend/src/main/java/com/example/neighbornetbackend/service/ContentProcessingService.java
- backend/src/main/java/com/example/neighbornetbackend/service/FileProcessingService.java
- frontend/src/components/ContentImportQuizGenerator.jsx
- frontend/src/components/CreateQuiz.jsx
Added feature can import PDF etc
> Added feature can import PDF etc

- railway.json
> deployment2

- railway.json
> deployment3

- Procfile
- backend/system.properties
- railway.json
> deployment4

- nixpacks.toml
- railway.json
> deployment5

- backend/Dockerfile
> fix version again

- backend/src/main/java/com/example/neighbornetbackend/config/GoogleCloudStorageConfig.java
> Added logger

- backend/src/main/java/com/example/neighbornetbackend/config/GoogleCloudStorageConfig.java
> please work

- backend/src/main/resources/application-prod.properties
- frontend_mobile/frontend_mobile/app/build.gradle.kts
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/VideoPlayer.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/api/ClassApiService.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/auth/ChatViewModel.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/di/NetworkModule.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/network/PaginatedClassResponse.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/network/StompClient.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/repository/ChatRepository.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/repository/ClassRepository.kt
- frontend_mobile/frontend_mobile/app/src/main/java/com/example/neighbornet/utils/UrlUtils.kt
> ready for presentation

- backend/src/main/java/com/example/neighbornetbackend/config/CacheConfig.java
- frontend/src/components/ClassCard.jsx
- frontend/src/components/PostsView.jsx
- frontend/src/components/UsersView.jsx
> small fixes

- frontend/src/components/SplashScreen/ClassDetails.jsx
- frontend/src/components/StudyRooms.jsx
> another fix

- frontend/src/components/Borrowing.jsx
- frontend/src/components/HomePage.jsx
- frontend/src/components/SplashScreen/ClassDetails.jsx
> fixing the styles

- frontend/src/components/Borrowing.jsx
- frontend/src/components/SplashScreen/ClassDetails.jsx
- frontend/src/components/SplashScreen/YourClasses.jsx
> fix styles again 2
